language: objective-c
osx_image: xcode8.2
cache: cocoapods
xcode_workspace: ./Example/incwavemountainsviewExample/incwavemountainsviewExample.xcworkspace
xcode_scheme: incwavemountainsviewExample
xcode_sdk: iphonesimulator
env:
  global:
    - SCAN_WORKSPACE='incwavemountainsviewExample.xcworkspace'
    - SCAN_SCHEME='incwavemountainsviewExample'
  matrix:
    - DEVICE="iPhone 6s"
    - DEVICE="iPhone 7"
install: 
      - bundle install
podfile: ./Example/incwavemountainsviewExample/Podfile
script:
   - bundle exec pod install --project-directory=./Example/incwavemountainsviewExample/
   - cd Example/incwavemountainsviewExample
   - travis_wait bundle exec fastlane run_test_travis;
   - cd -
notifications:
  email: false
branches:
  only:
  - master
  - "/^\\d+(\\.(x|\\d+)){1,2}$/"
  - "/^develop/"
  - "/^feature-./"
